# DO NOT EDIT- AUTOGENERATED

# Load from .profile.d
if [[ -d "$HOME/.bashrc.d/" ]]; then
  for BASHRC_CONFIG in ${HOME}/.bashrc.d/*.shinc ; do
    if [[ -f "${BASHRC_CONFIG}" ]] ; then
      source "${BASHRC_CONFIG}"
    fi
  done
fi
