# DO NOT EDIT THIS FILE IT IS AUTOGENERATED

# Load shell configs from .bashrc.d
if [ -d "$HOME/.bashrc.d" ]; then
  for config in $HOME/.bashrc.d/*.sh ; do
    if [ -f $config ] ; then
      source $config
    fi
  done
fi

