# DO NOT EDIT THIS FILE IT IS AUTOGENERATED

# Load shell configs from .profile.d
if [ -d "$HOME/.profile.d/" ]; then
  for config in $HOME/.profile.d/*.sh ; do
    if [ -f $config ] ; then
      source $config
    fi
  done
fi

source "$HOME/.bashrc"
