# DO NOT EDIT THIS FILE IT IS AUTOGENERATED

# Things common to all shells go in .profile
# - PATH
# - LANG

# Load from .profile.d
if [[ -d "$HOME/.profile.d/" ]]; then
  for PROFILE_CONFIG in ${HOME}/.profile.d/*.shinc ; do
    if [[ -f "${PROFILE_CONFIG}" ]] ; then
      source "${PROFILE_CONFIG}"
    fi
  done
fi

# Load shell config
if [[ ! -z "${BASH}" ]]; then
  source "${HOME}/.bashrc"
fi
